# Generated by Django 3.0.3 on 2020-04-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_invoice', '0002_auto_20200417_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='session_id',
            field=models.CharField(max_length=512),
        ),
    ]
